Update Code Summarization section
src-d/awesome-machine-learning-on-source-code pull request #103
Opened 2018-09-13 18:33 UTC by bdqnghi

Hi,

I would like to update 3 new papers about source code summarization. All of these are published in 2018.

Thanks

Signed-off-by: Nghi Bui bdqnghi@gmail.com

2018-09-13 19:11 UTC, vmarkovtsev approved these changes

2018-09-14 15:42 UTC, m09 requested changes

2018-09-14 15:42 UTC, m09 commented on README.md
> +* <img src="badges/7-pages-gray.svg" alt="11-pages" align="top"> [Summarizing Source Code with Transferred API Knowledge](https://xin-xia.github.io/publication/ijcai18.pdf) - Xing Hu, Ge Li, Xin Xia,
alt should be 7 pages

2018-09-14 15:42 UTC, m09 commented on README.md
> +* <img src="badges/6-pages-gray.svg" alt="11-pages" align="top"> [A Neural Framework for Retrieval and Summarization of Source Code](https://dl.acm.org/citation.cfm?id=3240471) - Qingying Chen, Mingh
alt should be 6 pages

2018-09-15 10:21 UTC, closed without merging