add "An Empirical Investigation into Learning Bug-Fixing Patches in the Wild via Neural Machine Translation"
src-d/awesome-machine-learning-on-source-code pull request #107
Opened 2018-09-27 08:21 UTC by monperrus

…

2018-09-27 18:57 UTC, EgorBu requested changes
Thanks for the article! Please signoff and update according to feedback

2018-09-27 18:57 UTC, EgorBu commented on README.md
> +* <img src="badges/6-pages-gray.svg" alt="6-pages" align="top"> [An Empirical Investigation into Learning Bug-Fixing Patches in the Wild via Neural Machine Translation](http://www.cs.wm.edu/~denys/pu
please add dot to the end of the line to keep style consistent.

2018-09-27 18:57 UTC, EgorBu commented on README.md
> +* <img src="badges/6-pages-gray.svg" alt="6-pages" align="top"> [An Empirical Investigation into Learning Bug-Fixing Patches in the Wild via Neural Machine Translation](http://www.cs.wm.edu/~denys/pu
```
Michele Tufano
College of William and Mary
Williamsburg, VA, USA
Cody Watson
College of William and Mary
Williamsburg, VA, USA
Gabriele Bavota
Università della Svizzera italiana (USI)
Lugano, Switzerland
Massimiliano Di Penta
University of Sannio
Benevento, Italy
Martin White
College of William and Mary
Williamsburg, VA, USA
Denys Poshyvanyk
College of William and Mary
Williamsburg, VA, USA
```
there are six authors of this paper - they should be mentioned.

2018-10-18 08:58 UTC, EgorBu commented
The article was added in https://github.com/src-d/awesome-machine-learning-on-source-code/pull/111

2018-10-18 08:58 UTC, closed without merging

2018-10-18 09:45 UTC, monperrus commented
Thanks. --Martin

On 10/18/18 10:59 AM, Egor Bulychev wrote:
>
> The article was added in #111
> <https://github.com/src-d/awesome-machine-learning-on-source-code/pull/111>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/src-d/awesome-machine-learning-on-source-code/pull/107#issuecomment-430931050>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAxDUrifOnWs-UvxMlISApGWqMaSQHG3ks5umEMIgaJpZM4W8I4L>.
>