Add 3 papers about AST differencing
src-d/awesome-machine-learning-on-source-code pull request #147
Opened 2018-11-30 09:36 UTC by warenlg

Signed-off-by: Waren Long <waren@sourced.tech>

Please fill the `[ ]` with an `x` to make sure that you read and followed the checklist

- [x] This addition is about Machine Learning __on Code__ specifically. General links should be added to [Awesome Machine Learning](https://github.com/josephmisiti/awesome-machine-learning) instead.
- [x] I have checked that the proposed addition is not already in the awesome list.
- [x] I have signed-off my commits as detailed [here](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md).
- [x] The links follow the link template:

        * [Title](URL) - Description.
    or

        * [Title](URL) - Description [Code](link to code).
- [x] The addition is correctly classified as a paper, blog post, talk, software or dataset.
- [x] The commit message must start with a verb (`Add …`, `Deprecate …`) and end without a dot. For exemple:

        Deprecate Theano software

2018-11-30 10:45 UTC, m09 commented
Thanks Waren for the PR! I think we should put the subsection in the related research section though since tree differencing is usually not using ML. Great additions otherwise :+1:

2018-11-30 11:09 UTC, m09 requested changes

2018-11-30 11:09 UTC, m09 commented on README.md
> +* <img src="badges/11-pages-gray.svg" alt="11-pages" align="top"> [Fine-grained and Accurate Source Code Differencing](https://hal.archives-ouvertes.fr/hal-01054552/document) - ean-Rémy Falleri, Flor
```suggestion
* <img src="badges/11-pages-gray.svg" alt="11-pages" align="top"> [Fine-grained and Accurate Source Code Differencing](https://hal.archives-ouvertes.fr/hal-01054552/document) - Jean-Rémy Falleri, Floréal Morandat, Xavier Blanc, Matias Martinez, Martin Monperrus, ASE 2014.
```

2018-12-03 17:43 UTC, bzz commented on README.md
> +* <img src="badges/12-pages-gray.svg" alt="12-pages" align="top"> [ClDiff: Generating Concise Linked Code Differences](https://chenbihuan.github.io/paper/ase18-huang-diff.pdf) - Kaifeng Huang, Bihuan
@warenlg why not linking source code as well as papers?

```suggestion
* <img src="badges/12-pages-gray.svg" alt="12-pages" align="top"> [ClDiff: Generating Concise Linked Code Differences](https://chenbihuan.github.io/paper/ase18-huang-diff.pdf) - Kaifeng Huang, Bihuan Chen, Xin Peng, Daihong Zhou, Ying Wang, Yang Liu, Wenyun Zhao, ASE 2018. [Code](https://github.com/FudanSELab/CLDIFF).
```

2018-12-05 07:25 UTC, m09 approved these changes

2018-12-05 07:34 UTC, merged