Add papers about Embeddings in Sotware Engineering
src-d/awesome-machine-learning-on-source-code pull request #54
Opened 2018-04-24 20:41 UTC by warenlg

Signed-off-by: Waren Long <waren@sourced.tech>

2018-04-25 12:22 UTC, eiso commented
Really nice addition @warenlg!

2018-04-27 13:00 UTC, vmarkovtsev requested changes

2018-04-27 13:00 UTC, vmarkovtsev commented on README.md
> +    - [Embeddings in Software Engineering](#embeddings-software-engineering)
The anchoer does not work, the correct one is `embeddings-in-software-engineering`

2018-04-27 13:01 UTC, vmarkovtsev approved these changes

2018-04-27 13:01 UTC, merged