Add more top tier conferences and papers Signed-off-by: Nghi Bui bdqn…
src-d/awesome-machine-learning-on-source-code pull request #66
Opened 2018-06-03 20:54 UTC by bdqnghi

I would suggest adding 2 more top tier conferences in soft engineering:
- ICSE: https://www.icse2018.org/
- FSE: https://conf.researchr.org/home/fse-2018

And 2 papers published in ICSE this year and FSE last year about source code modeling, one of them is mine :)

2018-06-04 09:16 UTC, vmarkovtsev approved these changes

2018-06-04 09:17 UTC, vmarkovtsev commented
Thank you so much for your contribution. You seem to miss a new line between the commit message title and the "signed-off-by" note. Could you please amend the commit and I will merge it at once!

2018-06-04 12:49 UTC, EgorBu requested changes
Thank you for the contribution! A couple of things before merging:
1) Please provide in PR comment with a short review of each article and conference to show why it should be included.
2) Minor fix in PR.

2018-06-04 12:49 UTC, EgorBu commented on README.md
> +* <img src="badges/4-pages-gray.svg" alt="12-pages" align="top"> [Hierarchical Learning of Cross-Language Mappings through Distributed Vector Representations for Code](https://bdqnghi.github.io/files
`"badges/4-pages-gray.svg" alt="12-pages"` - it should be 4 pages both

2018-06-07 05:56 UTC, vmarkovtsev commented
@egorbu (1) is already done. We cannot ask for a longer review because ourselves have not done it :-)

2018-06-08 15:41 UTC, vmarkovtsev commented
@bdqnghi can you please fix the DCO

2018-06-11 03:00 UTC, bdqnghi commented
Hi, i have updated the missing parts, can you check again?

2018-06-11 05:38 UTC, vmarkovtsev commented
All good, the signed-off-by is missing in the new commits and is still corrupted in the first one though.

2018-06-11 05:42 UTC, bdqnghi commented
ok, do i need to do something to fix it? or you merge it by yourself?

2018-06-11 06:03 UTC, closed without merging

2018-06-11 06:08 UTC, bdqnghi commented
ok since I made a lot of mistakes on this PR, i will close it and create a new one